version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  ms-escrita:
    build:
      context: ./ms-escrita
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - ./ms-escrita/.env

  ms-leitura:
    build:
      context: ./ms-leitura
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - ./ms-leitura/.env
      
networks:
  default:
    driver: bridge
